name: "Predict shit"
description: "Add predicted files to change given an issue"
inputs:
  github-token:
    description: "Github token"
    required: true

runs:
  using: "node12"
  main: "lib/index.js"
branding:
  icon: alert-circle
  color: blue
