name: "Test Issue Auto Labeling and Assigning"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
